/**
 * BaZi Glossary — tooltip explanations for all terms
 * Bilingual: Chinese primary, English secondary
 */

export interface GlossaryEntry {
  term: string;
  termEn: string;
  desc: string;
  descEn: string;
}

export const GLOSSARY: Record<string, GlossaryEntry> = {
  // Core concepts
  天干: { term: "天干", termEn: "Heavenly Stems", desc: "十个天干：甲乙丙丁戊己庚辛壬癸，代表天的能量变化，对应五行阴阳。", descEn: "The 10 Heavenly Stems represent celestial energy cycles, each mapped to a Yin/Yang polarity and one of the Five Elements." },
  地支: { term: "地支", termEn: "Earthly Branches", desc: "十二个地支：子丑寅卯辰巳午未申酉戌亥，对应十二生肖和时辰，代表地的能量。", descEn: "The 12 Earthly Branches correspond to the 12 Chinese zodiac animals and time periods." },
  四柱: { term: "四柱", termEn: "Four Pillars", desc: "由年柱、月柱、日柱、时柱组成，每柱一天干一地支，共八个字，故称「八字」。", descEn: "Year, Month, Day, and Hour Pillars — each with one Heavenly Stem and one Earthly Branch, forming the '8 Characters'." },
  日主: { term: "日主", termEn: "Day Master", desc: "日柱的天干，代表「自己」，是整个命盘分析的核心参照点。日主的五行属性决定了你的基本性格特征。", descEn: "The Heavenly Stem of the Day Pillar — it represents YOU. All other elements are analyzed in relation to the Day Master." },
  喜用神: { term: "喜用神", termEn: "Favorable Element", desc: "命盘中最需要补充的五行元素。通过佩戴对应颜色、选择对应方位和行业，可以增强运势。", descEn: "The element your chart needs most for balance. Wearing its colors, facing its direction, or working in related industries enhances fortune." },
  纳音: { term: "纳音", termEn: "Nayin Sound", desc: "六十甲子各有纳音，如「海中金」「炉中火」。纳音是天干地支组合后产生的五行特质，提供更细腻的命理信息。", descEn: "Each of the 60 Stem-Branch pairs has a poetic Nayin name describing its elemental quality, adding nuance to the reading." },
  藏干: { term: "藏干", termEn: "Hidden Stems", desc: "每个地支中暗藏1-3个天干。藏干代表内在的、隐藏的能量，影响深层性格和潜在机遇。", descEn: "Each Earthly Branch contains 1-3 hidden Heavenly Stems representing latent energies and hidden personality traits." },
  身强: { term: "身强", termEn: "Strong Day Master", desc: "日主得到较多生扶（同类五行或生我的五行多），精力充沛，适合主动出击、创业开拓。", descEn: "The Day Master has strong support — indicating vitality, assertiveness, and suitability for leadership roles." },
  身弱: { term: "身弱", termEn: "Weak Day Master", desc: "日主缺乏生扶，需要借助外力。适合合作、借势，选择喜用神对应的行业和方位发展。", descEn: "The Day Master lacks support — indicating need for partnerships, strategic alliances, and favorable element alignment." },

  // Pillars
  年柱: { term: "年柱", termEn: "Year Pillar", desc: "代表祖辈、家族根基、早年运势（1-16岁）。也反映一个人的社会形象和外在表现。", descEn: "Represents ancestry, family foundation, and early life (ages 1-16). Also reflects social image." },
  月柱: { term: "月柱", termEn: "Month Pillar", desc: "代表父母、成长环境、青年运势（17-32岁）。月柱是判断格局的关键依据。", descEn: "Represents parents, upbringing, and young adulthood (ages 17-32). Key pillar for determining chart patterns." },
  日柱: { term: "日柱", termEn: "Day Pillar", desc: "代表自己和配偶。日干是「我」，日支是「婚姻宫」。是命盘的核心。", descEn: "Represents self and spouse. The Day Stem is 'you', the Day Branch is the 'marriage palace'." },
  时柱: { term: "时柱", termEn: "Hour Pillar", desc: "代表子女、晚年运势（49岁以后）。也反映内心世界和潜意识。", descEn: "Represents children and later life (ages 49+). Also reflects inner world and subconscious." },

  // Ten Gods
  比肩: { term: "比肩", termEn: "Companion", desc: "与日主同五行同阴阳。代表朋友、同辈、竞争对手。性格独立自主，有主见。", descEn: "Same element, same polarity as Day Master. Represents friends, peers, competitors. Independent personality." },
  劫财: { term: "劫财", termEn: "Rob Wealth", desc: "与日主同五行异阴阳。代表兄弟姐妹、合作伙伴。有魄力但也有争夺之象。", descEn: "Same element, opposite polarity. Represents siblings, partners. Bold but competitive energy." },
  食神: { term: "食神", termEn: "Eating God", desc: "日主所生、同阴阳。代表才华、口福、表达能力。性格温和、有艺术天赋。", descEn: "Element generated by Day Master, same polarity. Represents talent, creativity, and eloquence." },
  伤官: { term: "伤官", termEn: "Hurting Officer", desc: "日主所生、异阴阳。代表叛逆、创新、技术。聪明但可能言辞犀利。", descEn: "Element generated by Day Master, opposite polarity. Represents innovation, rebellion, and sharp intellect." },
  偏财: { term: "偏财", termEn: "Indirect Wealth", desc: "日主所克、同阴阳。代表意外之财、投资收益、父亲。善于交际、慷慨大方。", descEn: "Element controlled by Day Master, same polarity. Represents windfall profits, investments, and social charm." },
  正财: { term: "正财", termEn: "Direct Wealth", desc: "日主所克、异阴阳。代表正当收入、妻子（男命）。勤恳踏实、理财有方。", descEn: "Element controlled by Day Master, opposite polarity. Represents salary income and financial prudence." },
  七杀: { term: "七杀", termEn: "Seven Killings", desc: "克日主、同阴阳。代表压力、权力、魄力。有领导力但也有攻击性。", descEn: "Element that controls Day Master, same polarity. Represents authority, pressure, and decisive power." },
  正官: { term: "正官", termEn: "Direct Officer", desc: "克日主、异阴阳。代表上司、法律、规则、丈夫（女命）。正直守规矩。", descEn: "Element that controls Day Master, opposite polarity. Represents authority figures, rules, and integrity." },
  偏印: { term: "偏印", termEn: "Indirect Seal", desc: "生日主、同阴阳。代表偏门学问、灵感、孤独。思维独特，适合研究和创作。", descEn: "Element that generates Day Master, same polarity. Represents unconventional knowledge and creative inspiration." },
  正印: { term: "正印", termEn: "Direct Seal", desc: "生日主、异阴阳。代表母亲、学历、名誉、贵人。性格慈祥、有文化底蕴。", descEn: "Element that generates Day Master, opposite polarity. Represents mother, education, reputation, and mentors." },

  // Five Elements
  木: { term: "木", termEn: "Wood", desc: "代表生长、仁慈、肝胆。方位：东方。颜色：绿色、青色。季节：春天。", descEn: "Growth, benevolence, liver. Direction: East. Colors: Green. Season: Spring." },
  火: { term: "火", termEn: "Fire", desc: "代表热情、礼仪、心脏。方位：南方。颜色：红色、紫色。季节：夏天。", descEn: "Passion, etiquette, heart. Direction: South. Colors: Red, Purple. Season: Summer." },
  土: { term: "土", termEn: "Earth", desc: "代表稳重、信用、脾胃。方位：中央。颜色：黄色、棕色。季节：四季交替。", descEn: "Stability, trust, spleen. Direction: Center. Colors: Yellow, Brown. Season: Transitions." },
  金: { term: "金", termEn: "Metal", desc: "代表果断、义气、肺部。方位：西方。颜色：白色、金色。季节：秋天。", descEn: "Decisiveness, loyalty, lungs. Direction: West. Colors: White, Gold. Season: Autumn." },
  水: { term: "水", termEn: "Water", desc: "代表智慧、灵活、肾脏。方位：北方。颜色：蓝色、黑色。季节：冬天。", descEn: "Wisdom, flexibility, kidneys. Direction: North. Colors: Blue, Black. Season: Winter." },

  // Relationships
  五行相生: { term: "五行相生", termEn: "Generation Cycle", desc: "木生火、火生土、土生金、金生水、水生木。相生代表滋养和促进的关系。", descEn: "Wood feeds Fire, Fire creates Earth, Earth bears Metal, Metal collects Water, Water nourishes Wood." },
  五行相克: { term: "五行相克", termEn: "Control Cycle", desc: "木克土、土克水、水克火、火克金、金克木。相克代表制约和控制的关系。", descEn: "Wood parts Earth, Earth dams Water, Water quenches Fire, Fire melts Metal, Metal chops Wood." },
  流年: { term: "流年", termEn: "Annual Influence", desc: "当前年份的天干地支对命盘的影响。每年的运势变化都由流年与原局的生克关系决定。", descEn: "The current year's Stem-Branch influence on your natal chart, determining this year's fortune trends." },
};

// Nayin (纳音) table — 60 Jiazi cycle
export const NAYIN_TABLE: Record<string, string> = {
  甲子: "海中金", 乙丑: "海中金", 丙寅: "炉中火", 丁卯: "炉中火", 戊辰: "大林木", 己巳: "大林木",
  庚午: "路旁土", 辛未: "路旁土", 壬申: "剑锋金", 癸酉: "剑锋金", 甲戌: "山头火", 乙亥: "山头火",
  丙子: "涧下水", 丁丑: "涧下水", 戊寅: "城头土", 己卯: "城头土", 庚辰: "白蜡金", 辛巳: "白蜡金",
  壬午: "杨柳木", 癸未: "杨柳木", 甲申: "泉中水", 乙酉: "泉中水", 丙戌: "屋上土", 丁亥: "屋上土",
  戊子: "霹雳火", 己丑: "霹雳火", 庚寅: "松柏木", 辛卯: "松柏木", 壬辰: "长流水", 癸巳: "长流水",
  甲午: "砂石金", 乙未: "砂石金", 丙申: "山下火", 丁酉: "山下火", 戊戌: "平地木", 己亥: "平地木",
  庚子: "壁上土", 辛丑: "壁上土", 壬寅: "金箔金", 癸卯: "金箔金", 甲辰: "覆灯火", 乙巳: "覆灯火",
  丙午: "天河水", 丁未: "天河水", 戊申: "大驿土", 己酉: "大驿土", 庚戌: "钗钏金", 辛亥: "钗钏金",
  壬子: "桑柘木", 癸丑: "桑柘木", 甲寅: "大溪水", 乙卯: "大溪水", 丙辰: "沙中土", 丁巳: "沙中土",
  戊午: "天上火", 己未: "天上火", 庚申: "石榴木", 辛酉: "石榴木", 壬戌: "大海水", 癸亥: "大海水",
};

// Lucky element recommendations
export const ELEMENT_RECOMMENDATIONS: Record<string, {
  colors: string; directions: string; industries: string; numbers: string;
  colorsEn: string; directionsEn: string; industriesEn: string;
}> = {
  木: { colors: "绿色、青色、翠色", directions: "东方、东南方", industries: "教育、出版、木材、服装、医药、文化", numbers: "3、8", colorsEn: "Green, Cyan, Emerald", directionsEn: "East, Southeast", industriesEn: "Education, Publishing, Fashion, Medicine, Culture" },
  火: { colors: "红色、紫色、橙色", directions: "南方", industries: "餐饮、能源、电子、娱乐、传媒、美容", numbers: "2、7", colorsEn: "Red, Purple, Orange", directionsEn: "South", industriesEn: "Food, Energy, Electronics, Entertainment, Media, Beauty" },
  土: { colors: "黄色、棕色、咖啡色", directions: "中央、东北、西南", industries: "房地产、建筑、农业、矿业、陶瓷", numbers: "5、10", colorsEn: "Yellow, Brown, Beige", directionsEn: "Center, Northeast, Southwest", industriesEn: "Real Estate, Construction, Agriculture, Mining" },
  金: { colors: "白色、金色、银色", directions: "西方、西北方", industries: "金融、科技、机械、汽车、法律、政府", numbers: "4、9", colorsEn: "White, Gold, Silver", directionsEn: "West, Northwest", industriesEn: "Finance, Technology, Law, Government, Automotive" },
  水: { colors: "蓝色、黑色、灰色", directions: "北方", industries: "物流、贸易、旅游、水利、渔业、IT", numbers: "1、6", colorsEn: "Blue, Black, Gray", directionsEn: "North", industriesEn: "Logistics, Trade, Tourism, IT, Shipping" },
};

// Day Master personality descriptions
export const DAY_MASTER_DESC: Record<string, { trait: string; traitEn: string }> = {
  甲: { trait: "甲木为参天大树，正直向上，有领导力和责任感。性格坚毅，有担当，但有时过于固执。", traitEn: "Like a towering tree — upright, ambitious, with natural leadership. Determined but sometimes stubborn." },
  乙: { trait: "乙木为花草藤蔓，柔韧灵活，善于适应环境。温柔善良，有艺术天赋，但可能优柔寡断。", traitEn: "Like a graceful vine — flexible, adaptable, artistic. Gentle and kind, but may be indecisive." },
  丙: { trait: "丙火为太阳之火，光明磊落，热情奔放。慷慨大方，有感染力，但容易冲动急躁。", traitEn: "Like the blazing sun — radiant, passionate, generous. Charismatic but can be impulsive." },
  丁: { trait: "丁火为烛光星火，温暖内敛，心思细腻。聪慧善思，有洞察力，但可能多虑敏感。", traitEn: "Like a candle flame — warm, introspective, perceptive. Thoughtful but can be overthinking." },
  戊: { trait: "戊土为高山大地，稳重厚实，值得信赖。包容心强，有耐力，但可能过于保守。", traitEn: "Like a mountain — solid, reliable, trustworthy. Patient and inclusive, but can be too conservative." },
  己: { trait: "己土为田园沃土，温润养人，善于照顾他人。细心周到，有服务精神，但容易委屈自己。", traitEn: "Like fertile farmland — nurturing, caring, service-oriented. Detail-minded but may sacrifice self." },
  庚: { trait: "庚金为刀剑利器，果断刚毅，有正义感。做事雷厉风行，但可能过于强势直接。", traitEn: "Like a sharp sword — decisive, just, action-oriented. Efficient but can be too forceful." },
  辛: { trait: "辛金为珠宝美玉，精致优雅，追求完美。品味高雅，有审美力，但可能过于挑剔。", traitEn: "Like a precious gem — refined, elegant, perfectionist. Tasteful but can be too critical." },
  壬: { trait: "壬水为江河大海，智慧包容，志向远大。思维开阔，有谋略，但可能不够脚踏实地。", traitEn: "Like a vast ocean — wise, broad-minded, ambitious. Strategic but may lack grounding." },
  癸: { trait: "癸水为雨露甘霖，温柔滋润，直觉敏锐。善解人意，有灵性，但可能过于多愁善感。", traitEn: "Like gentle rain — nurturing, intuitive, empathetic. Spiritually gifted but may be too sentimental." },
};
