"use client";

import Link from "next/link";
import { useLocale } from "@/lib/LocaleContext";
import BottomNav from "@/components/BottomNav";

export default function TermsPage() {
  const { t } = useLocale();

  return (
    <div className="min-h-screen bg-[#0a0814]">
      <div className="lg:hidden flex items-center h-11 px-4 border-b border-amber-400/10 sticky top-0 bg-[#0a0814] z-10">
        <Link href="/" className="text-amber-200/60 hover:text-amber-200 mr-3 text-lg">←</Link>
        <span className="font-semibold text-[15px] text-amber-100">{t("footer.terms")}</span>
      </div>

      <main className="max-w-3xl mx-auto px-4 py-8 lg:py-16 pb-24">
        <h1 className="text-2xl font-bold text-amber-100 mb-6">{t("footer.terms")}</h1>

        <div className="prose prose-sm prose-invert max-w-none space-y-4 text-amber-200/60 text-sm leading-relaxed">
          <h2 className="text-lg font-semibold text-amber-200/80">1. Acceptance of Terms</h2>
          <p>By using Kairós, you agree to these terms of service. If you do not agree, please do not use our platform.</p>

          <h2 className="text-lg font-semibold text-amber-200/80">2. Service Description</h2>
          <p>Kairós is a platform that provides AI-powered personality analysis and cultural wellness insights based on traditional Eastern philosophical frameworks. We do not provide medical, financial, or legal advice.</p>

          <h2 className="text-lg font-semibold text-amber-200/80">3. Disclaimer</h2>
          <p>All analysis and insights provided through our platform are generated by AI for entertainment, self-reflection, and personal development purposes only. Kairós makes no claims regarding predictive accuracy.</p>
          <p>You should not make important life, financial, medical, or legal decisions based solely on the analysis provided by our platform.</p>

          <h2 className="text-lg font-semibold text-amber-200/80">4. User Accounts</h2>
          <p>You are responsible for maintaining the security of your account. You must provide accurate information when creating an account.</p>

          <h2 className="text-lg font-semibold text-amber-200/80">5. Reviews and Content</h2>
          <p>Users may submit reviews that are honest and based on genuine experiences. We reserve the right to remove reviews that violate our guidelines.</p>

          <h2 className="text-lg font-semibold text-amber-200/80">6. Payment & Digital Products</h2>
          <p>Kairós offers paid digital products including AI-powered personality analysis reports. Payments are processed securely through Stripe.</p>
          <p><strong>Refund Policy:</strong> All digital products are delivered instantly upon purchase. Due to the nature of digital content, all sales are final and non-refundable once the report has been generated and delivered. By completing your purchase, you acknowledge and agree to this policy.</p>
          <p><strong>Pricing:</strong> Prices are displayed in USD and may vary. Kairós reserves the right to modify pricing at any time.</p>
          <p><strong>Consultations:</strong> Payments for direct consultations with masters are made between users and masters via LINE. Kairós does not process these payments.</p>

          <h2 className="text-lg font-semibold text-amber-200/80">7. Nature of Services</h2>
          <p>Kairós provides AI-powered personality and life analysis based on traditional Chinese metaphysical principles (BaZi / Four Pillars of Destiny) and Western astrology. These services are provided for <strong>entertainment and personal reflection purposes only</strong>.</p>
          <p>Our analysis reports are generated by artificial intelligence and should not be considered professional advice. You should not make important life, financial, medical, or legal decisions based solely on our analysis.</p>
          <p>Kairós makes no claims regarding the predictive accuracy of any analysis provided.</p>

          <h2 className="text-lg font-semibold text-amber-200/80">8. Limitation of Liability</h2>
          <p>Kairós is not liable for any damages arising from the use of our platform, any digital products purchased, or any consultations arranged through it. Our maximum liability is limited to the amount paid for the specific product or service in question.</p>

          <h2 className="text-lg font-semibold text-amber-200/80">9. Dispute Resolution</h2>
          <p>Any disputes related to purchases should first be raised with our support team at hello@kairos.app. We aim to respond within 48 hours. If a resolution cannot be reached, disputes will be governed by the laws of Hong Kong SAR.</p>

          <h2 className="text-lg font-semibold text-amber-200/80">10. Contact</h2>
          <p>For questions about these terms or refund requests, contact us at hello@kairos.app</p>
        </div>
      </main>

      <BottomNav />
    </div>
  );
}
